export const SPECIES = [
    { label: 'All Roadkill', value: 'All Roadkill' },
    { label: 'Unidentifiable', value: 'Unidentifiable' },
    { label: 'Antelope', value: 'Antelope' },
    { label: 'Badger', value: 'Badger' },
    { label: 'Bear', value: 'Bear' },
    { label: 'Beaver', value: 'Beaver' },
    { label: 'Bison', value: 'Bison' },
    { label: 'Bobcat', value: 'Bobcat' },
    { label: 'Cougar', value: 'Cougar' },
    { label: 'Coyote', value: 'Coyote' },
    { label: 'Desert Bighorn', value: 'Desert Bighorn' },
    { label: 'Domestic Cat', value: 'Domestic Cat' },
    { label: 'Domestic Cow', value: 'Domestic Cow' },
    { label: 'Domestic Dog', value: 'Domestic Dog' },
    { label: 'Domestic Horse', value: 'Domestic Horse' },
    { label: 'Domestic Sheep', value: 'Domestic Sheep' },
    { label: 'Eagle', value: 'Eagle' },
    { label: 'Elk', value: 'Elk' },
    { label: 'Golden eagle', value: 'Golden eagle' },
    { label: 'Gray Fox', value: 'Gray Fox' },
    { label: 'Great horned owl', value: 'Great horned owl' },
    { label: 'Greater sage grouse', value: 'Greater sage grouse' },
    { label: 'Guineafowl', value: 'Guineafowl' },
    { label: 'Hawk', value: 'Hawk' },
    { label: 'Horned owl', value: 'Horned owl' },
    { label: 'Kit Fox', value: 'Kit Fox' },
    { label: 'Marmot', value: 'Marmot' },
    { label: 'Moose', value: 'Moose' },
    { label: 'Mule Deer', value: 'Mule Deer' },
    { label: 'Osprey', value: 'Osprey' },
    { label: 'Owl', value: 'Owl' },
    { label: 'Pelican', value: 'Pelican' },
    { label: 'Pheasant', value: 'Pheasant' },
    { label: 'Porcupine', value: 'Porcupine' },
    { label: 'Pronghorn', value: 'Pronghorn' },
    { label: 'Rabbit/Hare', value: 'Rabbit/Hare' },
    { label: 'Raccoon', value: 'Raccoon' },
    { label: 'Red Fox', value: 'Red Fox' },
    { label: 'Red-tailed hawk', value: 'Red-tailed hawk' },
    { label: 'River Otter', value: 'River Otter' },
    { label: 'Rocky Mountain Goat', value: 'Rocky Mountain Goat' },
    { label: 'Striped Skunk', value: 'Striped Skunk' },
    { label: 'Turkey', value: 'Turkey' },
    { label: 'Turkey Vulture', value: 'Turkey Vulture' },
];
